# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            CME 252
description:      Introduction to Optimization
url:              http://ajfriend.github.io/
baseurl:          /

author:
  name:           'AJ Friend'
