# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            AJ Friend
description:      ICME PhD Student
url:              http://ajfriend.github.io/
baseurl:          /

author:
  name:           'AJ Friend'
