site_name: AJ Friend
docs_dir: src
site_dir: docs
repo_url: https://github.com/ajfriend/ajfriend.github.io
repo_name: ajfriend.github.io
edit_uri: blob/master/src/

nav:
  - About: index.md
  - Blog: blog
  - Notes: notes
  - Contact: contact.md


theme:
  name: material
  palette:
    primary: white
    accent: red
  icon:
    repo: fontawesome/brands/github

plugins:
  - git-revision-date-localized:
      type: date
  - search

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - smarty
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - codehilite
  - pymdownx.smartsymbols
  - pymdownx.betterem:
      smart_enable: all
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
