site_name: AJ Friend
docs_dir: src
site_dir: docs
repo_url: https://github.com/ajfriend/ajfriend.github.io
repo_name: ajfriend.github.io
edit_uri: blob/master/src/

theme:
  name: material
  palette:
    primary: white
    accent: red
  icon:
    repo: fontawesome/brands/github

plugins:
  - git-revision-date-localized:
      type: date
  - search

nav:
  - About: 'index.md'
  - Blog: 'blog.md'
  - Notes: 'notes.md'
  - Contact: 'contact.md'
