site_name: AJ Friend
repo_url: https://github.com/ajfriend/ajfriend.github.io
repo_name: ajfriend.github.io
edit_uri: blob/master/docs/

nav:
  - index.md
  - Blog: blog
  - Notes: notes
  - contact.md

theme:
  name: material
  palette:
    primary: white
    accent: red
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs

plugins:
  - git-revision-date-localized:
      type: date
  - search
  - mkdocs-jupyter

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - smarty
  - pymdownx.magiclink
  - pymdownx.inlinehilite
  - codehilite
  - pymdownx.smartsymbols
  - pymdownx.betterem:
      smart_enable: all
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true


extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
