export UV_NO_EDITABLE := "0"
export UV_OFFLINE := "0"  # toggle on when offline to avoid failures

_:
	just --list

lab:
	uv run jupyter lab

plot:
	uv run python plot/figs_edges.py
	uv run python plot/figs_labels.py
	uv run python plot/four_cells.py
	uv run python plot/figs_disk.py
	uv run python plot/figs_ring.py

purge:
	just _rm .venv
	just _rm '*.egg-info'
	just _rm '*.ipynb_checkpoints'
	just _rm '*.lock'
	just _rm build
	just _rm .claude
	rm -rf figs/*

_rm pattern:
    -@find . -name "{{pattern}}" -prune -exec rm -rf {} +
