export UV_NO_EDITABLE := "1"
export UV_OFFLINE := "1"  # toggle on when offline to avoid failures

_:
	just --list

setup:
	uv venv
	uv pip install -r requirements.txt
	uv pip install .

lab:
	@[ -d .venv ] || just setup
	uv run jupyter lab

plot:
	uv run python notebooks/figs.py

clean:
	just _rm .venv
	just _rm *.egg-info
	just _rm *.lock
	just _rm build

_rm pattern:
    -@find . -name "{{pattern}}" -prune -exec rm -rf {} +
